//-------------------------------------------------------------------------------------------------------------------------------------------//
// Projeto Megasoft 1 Versão 2.0 do Sistema de Tributos Municipais com Banco de Dados: IPTU. ITBI e ISS, com implementação básica do REFIS;
// Autor: Daniel Guedes Fukuyoshi Garcia;
//-------------------------------------------------------------------------------------------------------------------------------------------//
// Pacote View;
package View;
// Importações de códigos para implementação na Classe;
import Controller.MenuConsultaController;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

//-------------------------------------------------------------------------------------------------------------------------------------------//
// Classe MenuConsultaView;
public class MenuConsultaView extends javax.swing.JFrame {
    //---------------------------------------------------------------------------------------------------------------------------------------//
    // Atributos
    private final MenuConsultaController controller;
    
    //---------------------------------------------------------------------------------------------------------------------------------------//
    // Métodos Especiais
    // Construtor da Classe MenuConsultaView
    /**
     * Creates new form MenuConsultaView
     */
    public MenuConsultaView() {
        initComponents();
        // Declara atributo controller que recebe um controlador do tipo MenuConsultaController
        controller = new MenuConsultaController(this);
    }
    // Todos os getters e setters dos atributos da Classe;
    public JTextArea getAreaTextoConsulta() {
        return AreaTextoConsulta;
    }
    public void setAreaTextoConsulta(JTextArea AreaTextoConsulta) {
        this.AreaTextoConsulta = AreaTextoConsulta;
    }
    public JButton getBotaoConsultaDuam() {
        return BotaoConsultaDuam;
    }
    public void setBotaoConsultaDuam(JButton BotaoConsultaDuam) {
        this.BotaoConsultaDuam = BotaoConsultaDuam;
    }
    public JButton getBotaoConsultaPessoa() {
        return BotaoConsultaPessoa;
    }
    public void setBotaoConsultaPessoa(JButton BotaoConsultaPessoa) {
        this.BotaoConsultaPessoa = BotaoConsultaPessoa;
    }
    public JTextField getConsultaCpfCnpj() {
        return ConsultaCpfCnpj;
    }
    public void setConsultaCpfCnpj(JTextField ConsultaCpfCnpj) {
        this.ConsultaCpfCnpj = ConsultaCpfCnpj;
    }
    public JTextField getConsultaNome() {
        return ConsultaNome;
    }
    public void setConsultaNome(JTextField ConsultaNome) {
        this.ConsultaNome = ConsultaNome;
    }
    public JTable getTabelaConsulta() {
        return TabelaConsulta;
    }
    public void setTabelaConsulta(JTable TabelaConsulta) {
        this.TabelaConsulta = TabelaConsulta;
    }
    
    //---------------------------------------------------------------------------------------------------------------------------------------//
    // Métodos
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ConsultaNome = new javax.swing.JTextField();
        ConsultaCpfCnpj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BotaoConsultaDuam = new javax.swing.JButton();
        BotaoConsultaPessoa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaConsulta = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        AreaTextoConsulta = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Digite os dados para realizar a consulta que deseja vizualizar:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Consulta de DUAM's");

        jLabel1.setText("Nome:");

        ConsultaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaNomeActionPerformed(evt);
            }
        });

        ConsultaCpfCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaCpfCnpjActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF/CNPJ:");

        BotaoConsultaDuam.setText("Consultar DUAM's Individualmente");
        BotaoConsultaDuam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultaDuamActionPerformed(evt);
            }
        });

        BotaoConsultaPessoa.setText("Consultar Dados Pessoais e DUAM's");
        BotaoConsultaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultaPessoaActionPerformed(evt);
            }
        });

        TabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DUAM", "Valor", "Vencimento", "Tributo", "Cód. Barras"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TabelaConsulta);
        if (TabelaConsulta.getColumnModel().getColumnCount() > 0) {
            TabelaConsulta.getColumnModel().getColumn(0).setResizable(false);
            TabelaConsulta.getColumnModel().getColumn(1).setResizable(false);
            TabelaConsulta.getColumnModel().getColumn(2).setResizable(false);
            TabelaConsulta.getColumnModel().getColumn(3).setResizable(false);
            TabelaConsulta.getColumnModel().getColumn(4).setResizable(false);
        }

        AreaTextoConsulta.setEditable(false);
        AreaTextoConsulta.setColumns(20);
        AreaTextoConsulta.setRows(5);
        jScrollPane4.setViewportView(AreaTextoConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConsultaNome)
                            .addComponent(ConsultaCpfCnpj)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoConsultaPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoConsultaDuam))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConsultaNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConsultaCpfCnpj)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoConsultaPessoa)
                    .addComponent(BotaoConsultaDuam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaNomeActionPerformed
    
    private void ConsultaCpfCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaCpfCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaCpfCnpjActionPerformed

    private void BotaoConsultaDuamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultaDuamActionPerformed
        // Executa a função ConsultaDuam do controlador Controller
        controller.ConsultaDuam();
        
    }//GEN-LAST:event_BotaoConsultaDuamActionPerformed

    private void BotaoConsultaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultaPessoaActionPerformed
        // Executa a função ConsultaPessoa do controlador Controller
        controller.ConsultaPessoa();
        
    }//GEN-LAST:event_BotaoConsultaPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuConsultaView().setVisible(true);
        });
    }
    
    //---------------------------------------------------------------------------------------------------------------------------------------//
    // Atributos
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTextoConsulta;
    private javax.swing.JButton BotaoConsultaDuam;
    private javax.swing.JButton BotaoConsultaPessoa;
    private javax.swing.JTextField ConsultaCpfCnpj;
    private javax.swing.JTextField ConsultaNome;
    private javax.swing.JTable TabelaConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    //---------------------------------------------------------------------------------------------------------------------------------------//
    // Fim da Classe MenuConsultaView;
}
//-------------------------------------------------------------------------------------------------------------------------------------------//