//-------------------------------------------------------------------------------------------------------------------------------------------//
// Projeto Megasoft 1 Versão 2.0 do Sistema de Tributos Municipais com Banco de Dados: IPTU. ITBI e ISS, com implementação básica do REFIS;
// Autor: Daniel Guedes Fukuyoshi Garcia;
//-------------------------------------------------------------------------------------------------------------------------------------------//
// Pacote View;
package View;
// Importações de códigos para implementação na Classe;
import javax.swing.JOptionPane;

//-------------------------------------------------------------------------------------------------------------------------------------------//
// Classe MenuCadastroView;
public class MenuCadastroView extends javax.swing.JFrame {
    //---------------------------------------------------------------------------------------------------------------------------------------//
    // Métodos Especiais
    // Construtor da Classe Tributo
    public MenuCadastroView() {
        initComponents();
    }
    
    //---------------------------------------------------------------------------------------------------------------------------------------//
    // Métodos
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel2 = new javax.swing.JLabel();
        CadastraNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CadastraCpfCnpj = new javax.swing.JTextField();
        CadastraLogradouro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CadastraComplemento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CadastraCep = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CadastraBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CadastraCidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CadastraEstado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CadastraTelefone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CadastraWhatsapp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CadastraValorDuam = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CadastraVencimento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CadastraTributo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        BotaoCadastraDuam = new javax.swing.JButton();
        CadastroAreaTexto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Digite os seguintes dados para cadastrar um DUAM:");

        CadastraNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome:");

        CadastraCpfCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraCpfCnpjActionPerformed(evt);
            }
        });

        CadastraLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraLogradouroActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF/CNPJ:");

        jLabel5.setText("Logradouro:");

        CadastraComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraComplementoActionPerformed(evt);
            }
        });

        jLabel6.setText("Complemento:");

        jLabel7.setText("CEP:");

        jLabel8.setText("Bairro:");

        CadastraCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraCidadeActionPerformed(evt);
            }
        });

        jLabel9.setText("Cidade:");

        jLabel10.setText("Estado:");

        CadastraTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraTelefoneActionPerformed(evt);
            }
        });

        jLabel11.setText("Telefone:");

        CadastraWhatsapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraWhatsappActionPerformed(evt);
            }
        });

        jLabel12.setText("Whatsapp:");

        jLabel13.setText("Valor DUAM:");

        jLabel14.setText("Vencimento:");

        CadastraTributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraTributoActionPerformed(evt);
            }
        });

        jLabel15.setText("Tributo: (Sigla)");

        BotaoCadastraDuam.setText("Cadastrar DUAM");
        BotaoCadastraDuam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastraDuamActionPerformed(evt);
            }
        });

        CadastroAreaTexto.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de DUAM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoCadastraDuam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CadastroAreaTexto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CadastraLogradouro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CadastraCpfCnpj, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CadastraNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CadastraComplemento)
                            .addComponent(CadastraCep)
                            .addComponent(CadastraBairro)
                            .addComponent(CadastraCidade)
                            .addComponent(CadastraEstado)
                            .addComponent(CadastraTelefone)
                            .addComponent(CadastraWhatsapp)
                            .addComponent(CadastraValorDuam)
                            .addComponent(CadastraVencimento)
                            .addComponent(CadastraTributo))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CadastraNome)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CadastraCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastraLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CadastraComplemento)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CadastraCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CadastraBairro)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastraCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CadastraEstado)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CadastraTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CadastraWhatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CadastraValorDuam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastraVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastraTributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoCadastraDuam)
                .addGap(18, 18, 18)
                .addComponent(CadastroAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastraNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraNomeActionPerformed

    private void CadastraCpfCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraCpfCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraCpfCnpjActionPerformed

    private void CadastraLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraLogradouroActionPerformed

    private void CadastraComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraComplementoActionPerformed

    private void CadastraCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraCidadeActionPerformed

    private void CadastraTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraTelefoneActionPerformed

    private void CadastraWhatsappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraWhatsappActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraWhatsappActionPerformed

    private void CadastraTributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraTributoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraTributoActionPerformed

    private void BotaoCadastraDuamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastraDuamActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Página em Desenvolvimento!\nVolte em Breve!");
    }//GEN-LAST:event_BotaoCadastraDuamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCadastroView().setVisible(true);
            }
        });
    }
    
    //---------------------------------------------------------------------------------------------------------------------------------------//
    // Atributos
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastraDuam;
    private javax.swing.JTextField CadastraBairro;
    private javax.swing.JTextField CadastraCep;
    private javax.swing.JTextField CadastraCidade;
    private javax.swing.JTextField CadastraComplemento;
    private javax.swing.JTextField CadastraCpfCnpj;
    private javax.swing.JTextField CadastraEstado;
    private javax.swing.JTextField CadastraLogradouro;
    private javax.swing.JTextField CadastraNome;
    private javax.swing.JTextField CadastraTelefone;
    private javax.swing.JTextField CadastraTributo;
    private javax.swing.JTextField CadastraValorDuam;
    private javax.swing.JTextField CadastraVencimento;
    private javax.swing.JTextField CadastraWhatsapp;
    private javax.swing.JTextField CadastroAreaTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
    //---------------------------------------------------------------------------------------------------------------------------------------//
    // Fim da Classe MenuCadastroView;
}
//-------------------------------------------------------------------------------------------------------------------------------------------//
